# Generated by Django 5.2.11 on 2026-03-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_editora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editora',
            old_name='descricao',
            new_name='nome',
        ),
        migrations.AddField(
            model_name='editora',
            name='site',
            field=models.URLField(blank=True, null=True),
        ),
    ]
