# Generated by Django 5.2.11 on 2026-03-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_livro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='nome',
        ),
        migrations.AddField(
            model_name='livro',
            name='isbn',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name='livro',
            name='quantidade',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='titulo',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
